on:
  workflow_dispatch:
    inputs:
      ios_version:
        description: 'iOS version string (ex.: 2.0.17)'
        required: true
        type: string
      android_version:
        description: 'Android version string (ex.: 2.0.17)'
        required: true
        type: string
      deploy_ios:
        description: 'Whether iOS should be deployed'
        required: true
        type: boolean
        default: true
      deploy_android:
        description: 'Whether Android should be deployed'
        required: true
        type: boolean
        default: true

jobs:
    deploy-manual:
        name: "Deploy manually"
        runs-on: linux-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Deploy
              uses: ./
              with:
                  ios_version: ${{ github.event.inputs.ios_version }}
                  android_version: ${{ github.event.inputs.android_version }}
